spring:
  profiles:
    active: local
  application:
    name: product-api
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://mgkim.net:5432/postgres
    username: postgres
    password: 1
    hikari:
      connection-timeout: 250
      maximum-pool-size: 3
      max-lifetime: 1800000
      pool-name: hikari
  sql:
    init:
      mode: never
      platform: postgres
      schema-locations: classpath:schema-postgres.sql
      data-locations: classpath:data.sql

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: spring.**.vo; java.lang
